// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    // The CLI (migrate/studio) uses this URL — point it at the DIRECT connection,
    // since Neon's pooled URL can't run migrations reliably.
    url: env("DIRECT_URL"),
  },
});
