// Writes plain-SQL versions of the job order matrix for one category, for
// running in the Neon SQL editor instead of scripts/applyJobMatrix.ts:
//   prisma/sql/<slug>-apply.sql  fills the category with the matrix
//   prisma/sql/<slug>-undo.sql   puts the category back to empty
// Only for a category that has no jobs yet (the apply file refuses
// otherwise); a category with live jobs needs applyJobMatrix.ts, which
// renames jobs in place and keeps worker prices attached.
//
// Usage (from backend/): npx tsx scripts/jobMatrixToSql.ts "Device Repair"
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { loadMatrix, matrixBounds, matrixStartingPrice, type MatrixQuestion } from '../prisma/seeds/lib/jobMatrix';

const name = process.argv[2];
const matrix = loadMatrix().find((c) => c.name === name);
if (!matrix) throw new Error(`jobOrderMatrix.json has no category "${name}".`);

// What the undo file puts back: the category as it was before the matrix
// (live values as of 2026-09-25). Add an entry before generating for another
// empty category.
const UNDO_BASELINE: Record<string, { basePrice: number; placeholderQuestion: string | null }> = {
  'Device Repair': { basePrice: 1500, placeholderQuestion: 'Computer Repair' },
};
const baseline = UNDO_BASELINE[name];
if (!baseline) throw new Error(`Add "${name}" to UNDO_BASELINE (its pre-matrix starting price and placeholder question) first.`);

// Prisma generates ids client-side (cuid), so the SQL brings its own.
const newId = () => 'c' + crypto.randomBytes(12).toString('hex').slice(0, 24);
const str = (v: string | null | undefined) => (v == null ? 'NULL' : `'${v.replace(/'/g, "''")}'`);
const num = (v: number | null | undefined) => (v == null ? 'NULL::double precision' : `${v}::double precision`);

type Field = { id: string; q: MatrixQuestion; jobId: string | null; sortOrder: number };
const fields: Field[] = [];
let sortOrder = 0;
for (const q of matrix.commonQuestions) fields.push({ id: newId(), q, jobId: null, sortOrder: sortOrder++ });
const jobs = matrix.jobs.map((job, i) => {
  const id = newId();
  let quantityFieldId: string | null = null;
  for (const q of job.questions) {
    const f = { id: newId(), q, jobId: id, sortOrder: sortOrder++ };
    if (q.setsPrice) quantityFieldId = f.id;
    fields.push(f);
  }
  return { id, job, sortOrder: i, quantityFieldId };
});

// Same cap rule as applyJobMatrix.ts: largest booking x top tier x 1.25, next ₱1,000.
const largestJob = Math.max(
  ...matrix.jobs
    .filter((j) => j.pricingModel !== 'CUSTOM_QUOTE')
    .map((j) => matrixBounds(j.price!).maxPrice * (j.pricingModel === 'PER_UNIT' ? j.questions.find((q) => q.setsPrice)?.maxValue ?? 1 : 1))
);

const cat = str(matrix.name);
const catId = `(SELECT id FROM "ServiceType" WHERE name = ${cat})`;
const jobRows = jobs.map(({ id, job, sortOrder: so }) => {
  const quote = job.pricingModel === 'CUSTOM_QUOTE';
  const b = quote ? null : matrixBounds(job.price!);
  return `  (${str(id)}, ${str(job.name)}, ${so}, ${num(quote ? 0 : job.price)}, ${str(job.pricingModel)}, ${num(b?.minPrice)}, ${num(b?.maxPrice)}, ${str(job.unit)})`;
});
const fieldRows = fields.map(
  ({ id, q, sortOrder: so }) =>
    `  (${str(id)}, ${str(q.label)}, ${str(q.helpText)}, ${str(q.fieldType)}, ${q.required}, ${so}, ${num(q.minValue)}, ${num(q.maxValue)}, ${!!q.usedForMatching})`
);
const optionRows = fields.flatMap(({ id, q }) => (q.options ?? []).map((label, i) => `  (${str(newId())}, ${str(id)}, ${str(label)}, ${i})`));
const linkRows = fields.filter((f) => f.jobId).map((f) => `  (${str(f.id)}, ${str(f.jobId)})`);
const jobIds = jobs.map((j) => str(j.id)).join(', ');

const apply = `-- Job order matrix: ${matrix.name}
-- Generated by backend/scripts/jobMatrixToSql.ts from prisma/seeds/data/jobOrderMatrix.json.
-- Paste the whole file into the Neon SQL editor and run it once.
-- Everything runs in one transaction: if any statement fails, nothing is kept.
-- Fills an EMPTY category only (it stops if the category already has jobs).
-- To undo: ${path.basename(slugPath('undo'))}

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "ServiceType" WHERE name = ${cat}) THEN
    RAISE EXCEPTION 'No service category named ${matrix.name.replace(/'/g, "''")}';
  END IF;
  IF EXISTS (SELECT 1 FROM "ServiceTask" WHERE "serviceTypeId" = ${catId}) THEN
    RAISE EXCEPTION '${matrix.name.replace(/'/g, "''")} already has jobs; nothing was changed. Use scripts/applyJobMatrix.ts for a category with jobs.';
  END IF;
END $$;

-- Starting price on the category tile: the cheapest job.
UPDATE "ServiceType" SET "basePrice" = ${matrixStartingPrice(matrix)} WHERE name = ${cat};

-- Remove the old category-wide questions (and their options/worker match choices).
DELETE FROM "ServiceScopeField" WHERE "serviceTypeId" = ${catId};

-- Jobs (${jobs.length}). Worker price range = 80%–150% of the standard price.
INSERT INTO "ServiceTask" (id, "serviceTypeId", name, "sortOrder", "basePrice", "pricingModel", "minPrice", "maxPrice", "unitLabel", "isActive")
SELECT v.id, ${catId}, v.name, v.sort_order, v.base_price, v.pricing_model::"TaskPricingModel", v.min_price, v.max_price, v.unit, true
FROM (VALUES
${jobRows.join(',\n')}
) AS v(id, name, sort_order, base_price, pricing_model, min_price, max_price, unit);

-- Questions (${fields.length}: ${matrix.commonQuestions.length} common, the rest per job).
INSERT INTO "ServiceScopeField" (id, "serviceTypeId", label, "helpText", "fieldType", required, "sortOrder", "minValue", "maxValue", "usedForMatching", "updatedAt")
SELECT v.id, ${catId}, v.label, v.help_text, v.field_type::"ScopeFieldType", v.required, v.sort_order, v.min_value, v.max_value, v.used_for_matching, NOW()
FROM (VALUES
${fieldRows.join(',\n')}
) AS v(id, label, help_text, field_type, required, sort_order, min_value, max_value, used_for_matching);

-- Choices for Pick one / Pick any / Yes-No questions (${optionRows.length}).
INSERT INTO "ServiceScopeFieldOption" (id, "fieldId", label, "sortOrder") VALUES
${optionRows.join(',\n')};

-- Which job each per-job question is asked for.
INSERT INTO "ServiceScopeFieldTask" ("fieldId", "serviceTaskId") VALUES
${linkRows.join(',\n')};

-- Per-unit jobs: the number question that sets the price.
${jobs
  .filter((j) => j.quantityFieldId)
  .map((j) => `UPDATE "ServiceTask" SET "quantityScopeFieldId" = ${str(j.quantityFieldId)} WHERE id = ${str(j.id)};`)
  .join('\n')}

-- Sign every VERIFIED worker in the category up for every job at the standard price.
INSERT INTO "WorkerTaskSelection" (id, "workerProfileId", "serviceTaskId", "isActive", "updatedAt")
SELECT gen_random_uuid()::text, w."workerProfileId", t.id, true, NOW()
FROM "WorkerServiceCategory" w
JOIN "ServiceTask" t ON t.id IN (${jobIds})
WHERE w."serviceTypeId" = ${catId} AND w.status = 'VERIFIED'
ON CONFLICT ("workerProfileId", "serviceTaskId") DO UPDATE SET "isActive" = true, "updatedAt" = NOW();

INSERT INTO "WorkerTaskPrice" (id, "workerProfileId", "serviceTaskId", price, "unitPrice", "isActive", "updatedAt")
SELECT gen_random_uuid()::text, w."workerProfileId", t.id,
       CASE WHEN t."pricingModel" = 'FIXED' THEN t."basePrice" END,
       CASE WHEN t."pricingModel" = 'PER_UNIT' THEN t."basePrice" END,
       true, NOW()
FROM "WorkerServiceCategory" w
JOIN "ServiceTask" t ON t.id IN (${jobIds}) AND t."pricingModel" IN ('FIXED', 'PER_UNIT')
WHERE w."serviceTypeId" = ${catId} AND w.status = 'VERIFIED'
ON CONFLICT ("workerProfileId", "serviceTaskId") DO UPDATE
  SET price = EXCLUDED.price, "unitPrice" = EXCLUDED."unitPrice", "isActive" = true, "updatedAt" = NOW();

-- Widen any city price caps so bookings at the new prices aren't rejected
-- (₱0 up to the largest booking x top worker tier x 1.25).
UPDATE "PricingRule"
SET "minPrice" = 0,
    "maxPrice" = GREATEST("maxPrice", CEIL(${largestJob} * (SELECT GREATEST(COALESCE(MAX("tierProMultiplier"), 1.15), COALESCE(MAX("tierExpertMultiplier"), 1.3)) FROM "AppSettings") * 1.25 / 1000) * 1000),
    "updatedAt" = NOW()
WHERE LOWER("serviceType") = LOWER(${cat});

-- Summary (check these before trusting the result).
SELECT
  (SELECT COUNT(*) FROM "ServiceTask" WHERE "serviceTypeId" = ${catId} AND "isActive") AS active_jobs,          -- expect ${jobs.length}
  (SELECT COUNT(*) FROM "ServiceScopeField" WHERE "serviceTypeId" = ${catId}) AS questions,                       -- expect ${fields.length}
  (SELECT COUNT(*) FROM "ServiceTask" WHERE "serviceTypeId" = ${catId} AND "pricingModel" = 'PER_UNIT' AND "quantityScopeFieldId" IS NULL) AS per_unit_jobs_missing_count, -- expect 0
  (SELECT COUNT(*) FROM "WorkerTaskPrice" WHERE "serviceTaskId" IN (${jobIds})) AS worker_prices_set;

COMMIT;
`;

const undo = `-- Undo the job order matrix for ${matrix.name}: removes its jobs and
-- questions and restores the original placeholder question.
-- Generated by backend/scripts/jobMatrixToSql.ts. Runs in one transaction.
-- Stops without changing anything if a booking already uses one of the jobs.
-- City price caps widened by the apply file are left as they are.

BEGIN;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM "Booking" b JOIN "ServiceTask" t ON t.id = b."serviceTaskId" WHERE t."serviceTypeId" = ${catId}) THEN
    RAISE EXCEPTION 'A booking uses a ${matrix.name.replace(/'/g, "''")} job; deactivate the jobs in the admin editor instead.';
  END IF;
END $$;

-- Jobs go first (worker prices, selections and question links cascade with them).
DELETE FROM "ServiceTask" WHERE "serviceTypeId" = ${catId};
DELETE FROM "ServiceScopeField" WHERE "serviceTypeId" = ${catId};

${
  baseline.placeholderQuestion
    ? `INSERT INTO "ServiceScopeField" (id, "serviceTypeId", label, "fieldType", required, "sortOrder", "updatedAt")
VALUES (${str(newId())}, ${catId}, ${str(baseline.placeholderQuestion)}, 'TEXT', true, 0, NOW());`
    : '-- (the category had no questions before)'
}

UPDATE "ServiceType" SET "basePrice" = ${baseline.basePrice} WHERE name = ${cat};

SELECT
  (SELECT COUNT(*) FROM "ServiceTask" WHERE "serviceTypeId" = ${catId}) AS jobs,            -- expect 0
  (SELECT COUNT(*) FROM "ServiceScopeField" WHERE "serviceTypeId" = ${catId}) AS questions; -- expect ${baseline.placeholderQuestion ? 1 : 0}

COMMIT;
`;

function slugPath(kind: 'apply' | 'undo') {
  const slug = matrix!.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return path.join(__dirname, '..', 'prisma', 'sql', `${slug}-${kind}.sql`);
}
fs.mkdirSync(path.dirname(slugPath('apply')), { recursive: true });
fs.writeFileSync(slugPath('apply'), apply);
fs.writeFileSync(slugPath('undo'), undo);
console.log(`Wrote ${slugPath('apply')}\nWrote ${slugPath('undo')}`);
