-- AlterTable
ALTER TABLE "AppSettings" ADD COLUMN     "tierProMinRating" DOUBLE PRECISION NOT NULL DEFAULT 4.5,
ADD COLUMN     "tierProMinJobs" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "tierProMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.15,
ADD COLUMN     "tierExpertMinRating" DOUBLE PRECISION NOT NULL DEFAULT 4.8,
ADD COLUMN     "tierExpertMinJobs" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "tierExpertMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.3;
